### ISSUE TITLE
`ValueError: x and y must have same first dimension, but have shapes (6,) and (5,)`

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [DragonEggBedrockBreaking/Cube-Timer#3]
```py
Traceback (most recent call last):
  File "...path_to\Cube-Timer\src\cube_timer.py", line 757, in <module>
    plt.plot(solve_number, mean_solves)
  File "C:\Python\lib\site-packages\matplotlib\pyplot.py", line 3019, in plot
    return gca().plot(
  File "C:\Python\lib\site-packages\matplotlib\axes\_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "C:\Python\lib\site-packages\matplotlib\axes\_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "C:\Python\lib\site-packages\matplotlib\axes\_base.py", line 501, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (6,) and (5,)
```

**Comment by DragonEggBedrockBreaking** [comment]
fixed in 92308d6e7f5bd00c1c84bcd9078cd6f33b27b340
